---
# tasks file for ansible-role-zfsonlinux
# Inspiration from https://github.com/AlbanAndrieu/ansible-zfs/blob/master/tasks/zfs.yml

- name: Install ZFS repo
  apt_repository: repo={{ item }} update_cache=yes
  with_items:
     - ppa:zfs-native/stable

- name: Install ZFS
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
     - software-properties-common
     - debootstrap
     - zfs-initramfs
     - zfsutils
     - ubuntu-zfs
     #- zfs-fuse
     - grub2-common
     - grub-pc
     - spl
     - spl-dkms
     - zfs-dkms
  register: package_result
